# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Our ipython-notebook vagrant box is pre-built, but is based on trusty_am64
  # config.vm.box = "trusty_amd64"

  config.vm.box = "ipython-notebook"
  config.vm.box_url = "http://ccnmtl.columbia.edu/projects/ipython-notebook/ipython-notebook_trusty_amd64.box"

  # provision this box, with lots of python goodies
  config.vm.provision :shell, path: "bootstrap.sh"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. 
  # ipython notebook starts on 8888, so just map the host's 8888 to the guest's
  config.vm.network "forwarded_port", guest: 8888, host: 8888, auto_correct: true
end
